var lineHelper = new LineHelper();
lineHelper.drawLine("#left-instagram", ".dashboard");
lineHelper.drawLine("#left-facebook", ".dashboard");
lineHelper.drawLine("#left-pinterest", ".dashboard");
lineHelper.drawLine("#left-linkedin", ".dashboard");
lineHelper.drawLine("#left-telegram", ".dashboard");
lineHelper.drawLine("#left-twitter", ".dashboard");
lineHelper.drawLine("#left-skype", ".dashboard");
lineHelper.drawLine(".dashboard", "#right-instagram");
lineHelper.drawLine(".dashboard", "#right-twitter");
lineHelper.drawLine(".dashboard", "#right-facebook");
lineHelper.drawLine(".dashboard", "#right-skype");
//lineHelper.highlightLine("#left-twitter", ".dashboard","message");